// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.DomainClass.CaLamViec", b =>
                {
                    b.Property<string>("MaCa")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaCa")
                        .HasName("PK__CaLamVie__27258E7BE56C71B9");

                    b.ToTable("CaLamViec");
                });

            modelBuilder.Entity("DAL.DomainClass.ChatLieu", b =>
                {
                    b.Property<string>("MaChatLieu")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LoaiChatLieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaChatLieu")
                        .HasName("PK__ChatLieu__453995BC5A53678C");

                    b.ToTable("ChatLieu");
                });

            modelBuilder.Entity("DAL.DomainClass.ChucVu", b =>
                {
                    b.Property<string>("MaCv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaCV");

                    b.Property<string>("TenChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaCv")
                        .HasName("PK__ChucVu__27258E7662F837F4");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("DAL.DomainClass.Coupon", b =>
                {
                    b.Property<string>("MaCoupon")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("DieuKien")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<double?>("GiaTri")
                        .HasColumnType("float");

                    b.Property<string>("MoTa")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<string>("TenCoupon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaCoupon")
                        .HasName("PK__Coupon__44DC861CFF4C5E2C");

                    b.ToTable("Coupon");
                });

            modelBuilder.Entity("DAL.DomainClass.Doi", b =>
                {
                    b.Property<string>("MaDoi")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("DoiSangSp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LyDo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MaHdct")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaHDCT");

                    b.Property<DateTime?>("NgayDoi")
                        .HasColumnType("date");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDoi")
                        .HasName("PK__Doi__3D89F553A82D160F");

                    b.HasIndex("MaHdct");

                    b.ToTable("Doi");
                });

            modelBuilder.Entity("DAL.DomainClass.HoaDon", b =>
                {
                    b.Property<string>("MaHd")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaHD");

                    b.Property<string>("MaKh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaKH");

                    b.Property<string>("MaNv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaNV");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("date");

                    b.Property<double?>("TongTien")
                        .HasColumnType("float");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaHd")
                        .HasName("PK__HoaDon__2725A6E0A646428C");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("DAL.DomainClass.HoaDonChiTiet", b =>
                {
                    b.Property<string>("MaHdct")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaHDCT");

                    b.Property<double?>("DonGia")
                        .HasColumnType("float");

                    b.Property<string>("MaHd")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaHD");

                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaVoucher")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<double?>("TongTienSauVoucher")
                        .HasColumnType("float");

                    b.HasKey("MaHdct")
                        .HasName("PK__HoaDonCh__1419C129067DBD75");

                    b.HasIndex("MaHd");

                    b.HasIndex("MaSp");

                    b.HasIndex("MaVoucher");

                    b.ToTable("HoaDonChiTiet");
                });

            modelBuilder.Entity("DAL.DomainClass.KhachHang", b =>
                {
                    b.Property<string>("MaKh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaKH");

                    b.Property<double?>("Diem")
                        .HasColumnType("float");

                    b.Property<string>("MaRank")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDT");

                    b.HasKey("MaKh")
                        .HasName("PK__KhachHan__2725CF1E34FCD149");

                    b.HasIndex("MaRank");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("DAL.DomainClass.MauSac", b =>
                {
                    b.Property<string>("MaMau")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TenMau")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaMau")
                        .HasName("PK__MauSac__3A5BBB7DE9112DD8");

                    b.ToTable("MauSac");
                });

            modelBuilder.Entity("DAL.DomainClass.NhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaNV");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaCa")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaChucVu")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TenNhanVien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaNv")
                        .HasName("PK__NhanVien__2725D70A1974FC97");

                    b.HasIndex("MaCa");

                    b.HasIndex("MaChucVu");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("DAL.DomainClass.Rank", b =>
                {
                    b.Property<string>("MaRank")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("DieuKien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MucUuDai")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaRank")
                        .HasName("PK__RANKS__7AE118773D0E4582");

                    b.ToTable("RANKS");
                });

            modelBuilder.Entity("DAL.DomainClass.SanPham", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaSP");

                    b.Property<double?>("Gia")
                        .HasColumnType("float");

                    b.Property<string>("MaChatLieu")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaMau")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaSize")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaTh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaTH");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("date");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaSp")
                        .HasName("PK__SanPham__2725081C71FF4C4A");

                    b.HasIndex("MaChatLieu");

                    b.HasIndex("MaMau");

                    b.HasIndex("MaSize");

                    b.HasIndex("MaTh");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("DAL.DomainClass.Size", b =>
                {
                    b.Property<string>("MaSize")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("KichThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaSize")
                        .HasName("PK__Size__A787E7ED49F15BE9");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("DAL.DomainClass.Thongke", b =>
                {
                    b.Property<string>("MaThongKe")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaHd")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaHD");

                    b.Property<string>("MaNv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("NgayThongKe")
                        .HasColumnType("date");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TongDoanhThu")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("MaThongKe")
                        .HasName("PK__THONGKE__60E521F4A2F2FC5E");

                    b.HasIndex("MaHd");

                    b.HasIndex("MaNv");

                    b.ToTable("THONGKE");
                });

            modelBuilder.Entity("DAL.DomainClass.ThuongHieu", b =>
                {
                    b.Property<string>("MaTh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaTH");

                    b.Property<string>("TenThuongHieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaTh")
                        .HasName("PK__ThuongHi__27250075C13E4EC4");

                    b.ToTable("ThuongHieu");
                });

            modelBuilder.Entity("DAL.DomainClass.Voucher", b =>
                {
                    b.Property<string>("MaVoucher")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("DieuKien")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<double?>("GiaTri")
                        .HasColumnType("float");

                    b.Property<string>("MoTa")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<string>("TenVoucher")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVoucher")
                        .HasName("PK__Voucher__0AAC5B1111806D33");

                    b.ToTable("Voucher");
                });

            modelBuilder.Entity("DAL.DomainClass.Doi", b =>
                {
                    b.HasOne("DAL.DomainClass.HoaDonChiTiet", "MaHdctNavigation")
                        .WithMany("Dois")
                        .HasForeignKey("MaHdct")
                        .HasConstraintName("FK__Doi__MaHDCT__625A9A57");

                    b.Navigation("MaHdctNavigation");
                });

            modelBuilder.Entity("DAL.DomainClass.HoaDon", b =>
                {
                    b.HasOne("DAL.DomainClass.KhachHang", "MaKhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__HoaDon__MaKH__5AB9788F");

                    b.HasOne("DAL.DomainClass.NhanVien", "MaNvNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__HoaDon__MaNV__59C55456");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("DAL.DomainClass.HoaDonChiTiet", b =>
                {
                    b.HasOne("DAL.DomainClass.HoaDon", "MaHdNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("MaHd")
                        .HasConstraintName("FK__HoaDonChiT__MaHD__5F7E2DAC");

                    b.HasOne("DAL.DomainClass.SanPham", "MaSpNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("MaSp")
                        .HasConstraintName("FK__HoaDonChiT__MaSp__5D95E53A");

                    b.HasOne("DAL.DomainClass.Voucher", "MaVoucherNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("MaVoucher")
                        .HasConstraintName("FK__HoaDonChi__MaVou__5E8A0973");

                    b.Navigation("MaHdNavigation");

                    b.Navigation("MaSpNavigation");

                    b.Navigation("MaVoucherNavigation");
                });

            modelBuilder.Entity("DAL.DomainClass.KhachHang", b =>
                {
                    b.HasOne("DAL.DomainClass.Rank", "MaRankNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaRank")
                        .HasConstraintName("FK__KhachHang__MaRan__56E8E7AB");

                    b.Navigation("MaRankNavigation");
                });

            modelBuilder.Entity("DAL.DomainClass.NhanVien", b =>
                {
                    b.HasOne("DAL.DomainClass.CaLamViec", "MaCaNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaCa")
                        .HasConstraintName("FK__NhanVien__MaCa__40F9A68C");

                    b.HasOne("DAL.DomainClass.ChucVu", "MaChucVuNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaChucVu")
                        .HasConstraintName("FK__NhanVien__MaChuc__40058253");

                    b.Navigation("MaCaNavigation");

                    b.Navigation("MaChucVuNavigation");
                });

            modelBuilder.Entity("DAL.DomainClass.SanPham", b =>
                {
                    b.HasOne("DAL.DomainClass.ChatLieu", "MaChatLieuNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaChatLieu")
                        .HasConstraintName("FK__SanPham__MaChatL__4D5F7D71");

                    b.HasOne("DAL.DomainClass.MauSac", "MaMauNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaMau")
                        .HasConstraintName("FK__SanPham__MaMau__4B7734FF");

                    b.HasOne("DAL.DomainClass.Size", "MaSizeNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaSize")
                        .HasConstraintName("FK__SanPham__MaSize__4C6B5938");

                    b.HasOne("DAL.DomainClass.ThuongHieu", "MaThNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaTh")
                        .HasConstraintName("FK__SanPham__MaTH__4E53A1AA");

                    b.Navigation("MaChatLieuNavigation");

                    b.Navigation("MaMauNavigation");

                    b.Navigation("MaSizeNavigation");

                    b.Navigation("MaThNavigation");
                });

            modelBuilder.Entity("DAL.DomainClass.Thongke", b =>
                {
                    b.HasOne("DAL.DomainClass.HoaDon", "MaHdNavigation")
                        .WithMany("Thongkes")
                        .HasForeignKey("MaHd")
                        .HasConstraintName("FK__THONGKE__MaHD__65370702");

                    b.HasOne("DAL.DomainClass.NhanVien", "MaNvNavigation")
                        .WithMany("Thongkes")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__THONGKE__MaNv__662B2B3B");

                    b.Navigation("MaHdNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("DAL.DomainClass.CaLamViec", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("DAL.DomainClass.ChatLieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DAL.DomainClass.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("DAL.DomainClass.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("Thongkes");
                });

            modelBuilder.Entity("DAL.DomainClass.HoaDonChiTiet", b =>
                {
                    b.Navigation("Dois");
                });

            modelBuilder.Entity("DAL.DomainClass.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("DAL.DomainClass.MauSac", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DAL.DomainClass.NhanVien", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("Thongkes");
                });

            modelBuilder.Entity("DAL.DomainClass.Rank", b =>
                {
                    b.Navigation("KhachHangs");
                });

            modelBuilder.Entity("DAL.DomainClass.SanPham", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("DAL.DomainClass.Size", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DAL.DomainClass.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DAL.DomainClass.Voucher", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
